import Navbar from "@/components/header/Navbar";
import "./globals.css";
import Footer from "@/components/footer/Footer";

import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display:'swap',
  fallback: ['Arial', 'sans-serif'],
});

export const metadata = {
  title: "Hoster | dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
          <Navbar />
          {children}
          <Footer />
      </body>
    </html>
  );
}
